name: yutovo
title: Yutovo
base: core24
version: '1.4.1'
summary: Visual calculator inside a text editor
description: |
  Yutovo is an application for solving various mathematical problems. 
  Yutovo has a visual &quot;paper&quot; view for calculations. 
  It uses a generally accepted mathematical syntax to display formulas. 
  Yutovo is designed to solve everyday and engineering problems and can be used by different people and for different jobs.

grade: stable
confinement: strict

platforms:
  amd64:

source-code:
  - https://github.com/denprog/yutovo-logger
  - https://github.com/denprog/yutovo-calculator
  - https://github.com/denprog/yutovo-solver
  - https://github.com/denprog/yutovo-editor
  - https://github.com/denprog/yutovo-desktop

issues:
  - https://github.com/denprog/yutovo-desktop/issues

website:
  - https://yutovo.com

license: GPL-3.0-only

contact: https://yutovo.com

icon: yutovo.png
  
parts:
  spdlog:
    plugin: cmake
    source: https://github.com/gabime/spdlog.git
    source-tag: v1.15.3
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/app
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app
      craftctl default
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE

  yutovo-logger:
    plugin: cmake
    source: https://github.com/denprog/yutovo-logger.git
    source-tag: v1.0.4
    cmake-parameters:
      - -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/app
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app
      export YUTOVO_DEPLOY=$CRAFT_STAGE/app
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app
      make -j$(nproc)
      make install
    build-packages:
      - pkg-config
    after: [spdlog]

  boost:
    plugin: dump
    source: https://archives.boost.io/release/1.83.0/source/boost_1_83_0.zip
    source-checksum: sha256/c86bd9d9eef795b4b0d3802279419fde5221922805b073b9bd822edecb1ca28e
    source-type: zip
    build-packages:
      - g++
      - python3
      - make
      - unzip
      - yacc
    override-build: |
      cd $SNAPCRAFT_PART_SRC/boost_1_83_0
      ./bootstrap.sh --prefix=$SNAPCRAFT_PART_INSTALL/app --with-libraries=iostreams
      ./b2 -j$(nproc) install link=static variant=release cxxflags='-fPIE -fstack-protector-strong -D_FORTIFY_SOURCE=2' --layout=system
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE

  gmp:
    plugin: cmake
    source: https://github.com/sethtroisi/libgmp.git
    source-depth: 1
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/include
      mkdir -p $CRAFT_PART_INSTALL/app/lib
      cd $CRAFT_PART_SRC
      ./.bootstrap
      ./configure --enable-static --disable-shared --enable-cxx --libdir=$CRAFT_PART_INSTALL/app/lib/ --prefix=$CRAFT_PART_INSTALL/app/
      make -j$(nproc) && make install
    build-packages:
      - build-essential
      - pkg-config
      - m4
      - gawk
      - autoconf
      - automake
      - libtool
      - texinfo
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE

  mpfr:
    plugin: cmake
    source: https://gitlab.inria.fr/mpfr/mpfr.git
    source-tag: 4.2.1
    source-depth: 1
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/include
      cd $CRAFT_PART_SRC
      ./autogen.sh
      ./configure --enable-static --disable-shared --prefix=$CRAFT_PART_INSTALL/app/ --with-gmp-include=$CRAFT_STAGE/app/include \
        --with-gmp-lib=$CRAFT_STAGE/app/lib
      make -j$(nproc) && make install
    build-packages:
      - pkg-config
      - build-essential
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE
    after: [gmp]

  rapidjson:
    plugin: cmake
    source: https://github.com/Tencent/rapidjson.git
    source-tag: v1.1.0
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/include
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DRAPIDJSON_BUILD_TESTS=OFF \
        -DRAPIDJSON_BUILD_THIRDPARTY_GTEST=OFF -DRAPIDJSON_BUILD_DOC=OFF -DCMAKE_CXX_FLAGS="-Wno-class-memaccess -Wno-implicit-fallthrough"
      make -j$(nproc) && make install
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE

  libharu:
    plugin: cmake
    source: https://github.com/libharu/libharu.git
    source-tag: v2.4.4
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/include
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DBUILD_SHARED_LIBS=OFF
      make -j$(nproc) && make install
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE

  stb-image:
    plugin: dump
    source: .
    override-pull: |
      curl -L -o stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h
      curl -L -o stb_image_write.h https://raw.githubusercontent.com/nothings/stb/master/stb_image_write.h
    organize:
      stb_image.h: app/include/stb_image/stb_image.h
      stb_image_write.h: app/include/stb_image/stb_image_write.h
    stage:
      - app/include/stb_image/stb_image.h
      - app/include/stb_image/stb_image_write.h

  yutovo-calculator:
    plugin: cmake
    source: https://github.com/denprog/yutovo-calculator.git
    source-tag: v1.3.3
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app
      mkdir -p $CRAFT_PART_INSTALL/app/lib
      export YUTOVO_DEPLOY=$CRAFT_STAGE/app
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app/lib/cmake \
        -DBUILD_TESTS=OFF
      make -j$(nproc) && make install
    build-packages:
      - pkg-config
      - build-essential
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE
    after: [mpfr, boost, yutovo-logger]

  yutovo-solver:
    plugin: cmake
    source: https://github.com/denprog/yutovo-solver.git
    source-tag: v1.1.5
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/lib
      export YUTOVO_DEPLOY=$CRAFT_STAGE/app
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app/lib/cmake
      make -j$(nproc) && make install
    build-packages:
      - pkg-config
      - build-essential
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE
    after: [yutovo-calculator, rapidjson]

  mathgl:
    plugin: cmake
    source: http://downloads.sourceforge.net/mathgl/mathgl-8.0.3.tar.gz
    source-checksum: sha256/9bba9ee6a0f86d1b8f3f3ba0374d3cb776f772dbb6f1a01684ca6c0bd56204d6
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/lib
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app/lib/cmake \
        -Denable-openmp=False -Denable-png=False -Denable-opengl=False
      make -j$(nproc) && make install
    build-packages:
      - pkg-config
      - build-essential
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE/

  yutovo-editor:
    plugin: cmake
    source: https://github.com/denprog/yutovo-editor.git
    source-tag: v1.4.1
    override-build: |
      set -e
      mkdir -p $CRAFT_PART_INSTALL/app/lib
      export YUTOVO_DEPLOY=$CRAFT_STAGE/app
      cmake $CRAFT_PART_SRC -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app/lib/cmake \
        -DBUILD_TESTS=OFF
      make -j$(nproc) && make install
    build-packages:
      - pkg-config
      - build-essential
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE
    after: [yutovo-solver, mathgl, libharu, stb-image]

  yutovo-server:
    plugin: dump
    source: https://github.com/denprog/yutovo-server.git
    source-tag: v1.1.8
    source-depth: 1
    override-stage: |
      set -e
      mkdir -p $CRAFT_STAGE/app/bin
      cp -r $CRAFT_PART_SRC/library $CRAFT_STAGE/app/bin
    override-prime: |
      true

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - breeze-icon-theme
      - kde-style-breeze
      - qt5-style-plugins
      - qt5-gtk-platformtheme
      - shared-mime-info
      - libqt5gui5
      - locales-all
      - xdg-user-dirs

  yutovo-desktop:
    plugin: cmake
    source: https://github.com/denprog/yutovo-desktop.git
    source-tag: v1.4.1
    build-packages:
      - rsync
      - qttools5-dev-tools
      - libfontconfig1-dev
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/app
      export YUTOVO_DEPLOY=$CRAFT_STAGE/app
      cmake $CRAFT_PART_SRC -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/app -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=$CRAFT_STAGE/app/lib \
        -DCMAKE_PREFIX_PATH=$CRAFT_STAGE/app/lib/cmake -DCMAKE_EXE_LINKER_FLAGS="-L$CRAFT_STAGE/app/lib"
      make -j$(nproc) && make install
      cp $CRAFT_PART_SRC/setup/Snap/run.sh $CRAFT_STAGE/app/bin/
      cp $CRAFT_PART_SRC/setup/yutovo.desktop $CRAFT_STAGE/app/
      cp $CRAFT_PART_SRC/setup/yutovo.png $CRAFT_STAGE/app/application-x-yutovo.png
      cp $CRAFT_PART_SRC/setup/yutovo.xml $CRAFT_STAGE/app/
      cp $CRAFT_PART_SRC/setup/com.yutovo.yutovo.metainfo.xml $CRAFT_STAGE/app/
      cp $CRAFT_PART_SRC/setup/yutovo-16.png $CRAFT_STAGE/app/
      cp $CRAFT_PART_SRC/setup/yutovo-32.png $CRAFT_STAGE/app/
      cp $CRAFT_PART_SRC/setup/yutovo-64.png $CRAFT_STAGE/app/
    override-stage: |
      set -e
      cp -r $CRAFT_PART_INSTALL/app $CRAFT_STAGE
      cp $CRAFT_PART_BUILD/src/*.qm $CRAFT_STAGE/app/bin/
    override-prime: |
      rm $CRAFT_PRIME/app/lib/*.a || true
      rm -rf $CRAFT_PRIME/app/include
      mkdir -p $CRAFT_PRIME/app/bin
      mkdir -p $CRAFT_PRIME/usr/share/metainfo
      mkdir -p $CRAFT_PRIME/usr/share/mime/packages
      mkdir -p $CRAFT_PRIME/usr/share/icons/hicolor/16x16/apps/
      mkdir -p $CRAFT_PRIME/usr/share/icons/hicolor/32x32/apps/
      mkdir -p $CRAFT_PRIME/usr/share/icons/hicolor/64x64/apps/
      rsync -a --update $CRAFT_STAGE/app/bin/ $CRAFT_PRIME/app/bin/
      cp -u $CRAFT_STAGE/app/yutovo.desktop $CRAFT_PRIME/app/yutovo.desktop
      cp $CRAFT_STAGE/app/com.yutovo.yutovo.metainfo.xml $CRAFT_PRIME/usr/share/metainfo/
      cp $CRAFT_STAGE/app/application-x-yutovo.png $CRAFT_PRIME/
      cp $CRAFT_STAGE/app/yutovo-16.png $CRAFT_PRIME/usr/share/icons/hicolor/16x16/apps/yutovo.png
      cp $CRAFT_STAGE/app/yutovo-32.png $CRAFT_PRIME/usr/share/icons/hicolor/32x32/apps/yutovo.png
      cp $CRAFT_STAGE/app/yutovo-64.png $CRAFT_PRIME/usr/share/icons/hicolor/64x64/apps/yutovo.png
      cp $CRAFT_STAGE/app/yutovo.xml $CRAFT_PRIME/usr/share/mime/packages/
      chmod +x $CRAFT_PRIME/app/bin/run.sh
      update-mime-database $CRAFT_PRIME/usr/share/mime
      cd $CRAFT_PRIME/usr/lib/x86_64-linux-gnu || exit 0
      rm -f \
        libicutest.so.* \
        libdconf.so.* \
        libgdk_pixbuf_xlib-2.0.so.* \
        libvulkan.so.* \
        || true
      rm -f libEGL_mesa.so.* libGLX_mesa.so.*
      rm -rf $CRAFT_PRIME/usr/share/mathgl
    after: [yutovo-editor, yutovo-server, desktop-qt5]

apps:
  yutovo-desktop:
    command-chain:
      - bin/desktop-launch
    command: app/bin/run.sh
    environment:
      DISABLE_WAYLAND: 1
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      QT_STYLE_OVERRIDE: "Breeze"
      GIO_EXTRA_MODULES: ""
      LD_LIBRARY_PATH: $SNAP/app/lib:$LD_LIBRARY_PATH
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
      - gsettings
    desktop: app/yutovo.desktop
